FROM node:20 AS build
WORKDIR /app
COPY package.json package-lock.json* ./
COPY tsconfig*.json ./
COPY public ./public
COPY src ./src
RUN npm ci
RUN npm run build

FROM nginx:stable-alpine AS runtime
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
